import CaveFactory from '@/model/factories/cave-factory';

export default
{
    toJSON( aCaveLevel ) {
        return {
            x: aCaveLevel.startX,
            y: aCaveLevel.startY,
            w: aCaveLevel.width,
            h: aCaveLevel.height,
            t: aCaveLevel.terrain.join( "" ) // (int values)
        };
    },
    fromJSON( aJSON ) {
        const terrain = aJSON.t.split( "" ); // split integer values to Array
        let i       = terrain.length;
        while ( i-- ) {
            terrain[ i ] = parseInt( terrain[ i ], 10 );    // String to numerical
        }

        const out = CaveFactory.createCaveLevel( aJSON.w, aJSON.h, terrain );

        out.startX = aJSON.x;
        out.startY = aJSON.y;

        // exits and treasures are part from the terrain and generated by the CaveLevel constructor

        return out;
    }
};
