import Vue  from 'vue';
import Vuex from 'vuex';
import RPG  from './rpg.vue';
import store from './store';
// when hosted on igorski.nl the service workers are generated by the server
// if your local version requires service worker support, uncomment the next line
//import './registerServiceWorker';

Vue.config.productionTip = false;
Vue.use( Vuex );

new Vue({
    store: new Vuex.Store( store ),
    render: h => h( RPG )
}).$mount('#app');
